### ISSUE TITLE
Erro in famdb.py

### ISSUE THREAD

**Issue by ld9866** [Dfam-consortium/FamDB#12]
Dear developer:
I am trying the pipeline: https://github.com/shohei-kojima/MEGAnE/wiki/Prepare-a-custom-repeat-library-and-annotation-(mostly-for-analysis-of-non-human-WGS)

The step is ok and there are no problem.
# download Dfam repeat library
wget https://www.dfam.org/releases/Dfam_3.2/families/Dfam_curatedonly.h5.gz
gzip -d Dfam_curatedonly.h5.gz

But when we use the code:

famdb.py -i ./Dfam_curatedonly.h5 families -f embl -ad rattus > Dfam_custom.embl

it will showed: ERROR:famdb_globals:Please specify a file to operate on with the -i/--file option

l also tried the code:

/home/lidong/Software/FamDB-master/famdb.py -i /home/lidong/06.MEGAnE/dfam/Dfam_curatedonly.h5 names rattus
# showed:
ERROR:famdb_globals:Please specify a file to operate on with the -i/--file option.
Double-Check Command: 'str' object has no attribute 'resolve_names'

I don't know what caused this, because I used famdb a long time ago and it was very useful, is it the problem of this library?

**Comment by asgray** [comment]
The issue is that you're using the newest version of FamDB with an older version of Dfam. FamDB 1.0+ only works with Dfam 3.8, for any older versions of Dfam, you need FamDB 0.4.3 or older.
